### ISSUE TITLE
error in cargo build 

### ISSUE THREAD

**Issue by fengsx** [zu1k/srun#31]
cargo version: cargo 1.69.0-nightly
rustc version: rustc 1.69.0-nightly (e1eaa2d5d 2023-02-06)

<img width="497" alt="1675742155961" src="https://user-images.githubusercontent.com/7709602/217144361-d1a20f71-a9a6-4590-86dc-ec3fa012e63b.png">

![image](https://user-images.githubusercontent.com/7709602/217144421-659bffac-544f-4d5a-92f3-c64a04cd14c4.png)

**Comment by fengsx** [comment]
知道了，是 build 的时候需要加一个变量 `AUTH_SERVER_IP=xxx cargo build`

**Comment by zu1k** [comment]
![image](https://user-images.githubusercontent.com/42370281/217739959-c77fe378-09bf-4277-8447-b6ebf6ca6d51.png)

**Comment by fengsx** [comment]
rust 这语言太简单了，只学亿次就可以了:-(
