### ISSUE TITLE
减少默认的登录重试次数

### ISSUE THREAD

**Issue by Duanyll** [zu1k/srun#37]
默认情况下登录失败重试10次，测试时直接导致账号被rate limit限制登录了

**Comment by zu1k** [comment]
之前没有遇到类似的反馈，你可以提供你遇到的版本号并测试一下具体的限制条件吗

**Comment by XYZliang** [comment]
我也一样，换ip、换账号，都还是会显示被限制了。希望能出个debug模式或者将完整的日志输出

**Comment by zu1k** [comment]
> 我也一样，换ip、换账号，都还是会显示被限制了。希望能出个debug模式或者将完整的日志输出

目前已经是输出服务端返回的完整内容。你们遇到问题的srun版本是什么？是 https://github.com/zu1k/srun/discussions/8 里的版本吗？

**Comment by zu1k** [comment]
It has been modified to retry 3 times with an interval of 1s.
